# Publish all joint states -----------------------------------
  joint_state_controller:
    type: joint_state_controller/JointStateController
    publish_rate: 50

  # Mode controllers used to switch between control methods ----------------------------
  position_joint_mode_controller:
    type: joint_mode_controller/JointModeController
    joint_mode: 1 # position

  velocity_joint_mode_controller:
    type: joint_mode_controller/JointModeController
    joint_mode: 2 # velocity

  # Position - Right and Left Joint Position Trajectory Controllers -------------------
  tr5_position_trajectory_controller:
    type: "position_controllers/JointTrajectoryController"
    joints:
      - tr5shoulder_pan_joint
      - tr5shoulder_lift_joint
      - tr5elbow_joint
      - tr5wrist_1_joint
      - tr5wrist_2_joint
      - tr5gripper_1_joint
      - tr5gripper_2_joint

    constraints:
      goal_time: 2.0                   # Defaults to zero
      stopped_velocity_tolerance: 0.1 # Defaults to 0.01
      tr5shoulder_pan_joint:
        trajectory: 0
        goal: 0.2
      tr5shoulder_lift_joint:
        trajectory: 0
        goal: 0.2
      tr5elbow_joint:
        trajectory: 0
        goal: 0.2
      tr5wrist_1_joint:
        trajectory: 0
        goal: 0.2
      tr5wrist_2_joint:
        trajectory: 0
        goal: 0.2
      tr5gripper_1_joint:
        trajectory: 0
        goal: 0.2
      tr5gripper_2_joint:
        trajectory: 0
        goal: 0.2

    state_publish_rate:  50 # Defaults to 50
    action_monitor_rate: 20 # Defaults to 20
    #hold_trajectory_duration: 0 # Defaults to 0.5



  # Velocity - Right and Left Joint Velocity Trajectory Controllers -------------------
  tr5_velocity_trajectory_controller:
    type: "velocity_controllers/JointTrajectoryController"
    joints:
      - tr5shoulder_pan_joint
      - tr5shoulder_lift_joint
      - tr5elbow_joint
      - tr5wrist_1_joint
      - tr5wrist_2_joint
      - tr5gripper_1_joint
      - tr5gripper_2_joint

    constraints:
      goal_time: 2.0                   # Defaults to zero
      stopped_velocity_tolerance: 0.4 # Defaults to 0.01
      tr5shoulder_pan_joint:
        trajectory: 0
        goal: 0.2
      tr5shoulder_lift_joint:
        trajectory: 0
        goal: 0.2
      tr5elbow_joint:
        trajectory: 0
        goal: 0.2
      tr5wrist_1_joint:
        trajectory: 0
        goal: 0.2
      tr5wrist_2_joint:
        trajectory: 0
        goal: 0.2
      tr5gripper_1_joint:
        trajectory: 0
        goal: 0.2
      tr5gripper_2_joint:
        trajectory: 0
        goal: 0.2

    gains:
      tr5shoulder_pan_joint: {p: 2.0,  i: 0.01, d: 1.0, i_clamp: 1}
      tr5shoulder_lift_joint: {p: 3.0,  i: 0.01, d: 1.0, i_clamp: 1}
      tr5elbow_joint: {p: 3.0,  i: 0.01, d: 1.0, i_clamp: 1}
      tr5wrist_1_joint: {p: 3.0,  i: 0.01, d: 1.0, i_clamp: 1}
      tr5wrist_2_joint: {p: 3.0,  i: 0.01, d: 1.0, i_clamp: 1}
      tr5gripper_1_joint: {p: 3.0,  i: 0.01, d: 1.0, i_clamp: 1}
      tr5gripper_2_joint: {p: 3.0,  i: 0.01, d: 1.0, i_clamp: 1}

    state_publish_rate:  50 # Defaults to 50
    action_monitor_rate: 20 # Defaults to 20
    #hold_trajectory_duration: 0 # Defaults to 0.5

