<?xml version="1.0"?>
<robot xmlns:xacro="http://www.ros.org/wiki/xacro">

    <xacro:include filename="$(find tr5_description)/urdf/tr5.transmission.xacro" />
    <!--<xacro:include filename="$(find ur_description)/urdf/ur.gazebo.xacro" />-->

    <property name="pi" value="3.14159265" />

    <!-- @todo Inertia parameters -->
    <property name="base_mass" value="4.0" />  <!-- This mass might be incorrect -->
    <property name="shoulder_mass" value="3.7000" />
    <property name="arm_mass" value="8.3930" />
    <property name="upper_arm_mass" value="8.3930" />
    <property name="forearm_mass" value="2.2750" />
    <property name="wrist_1_mass" value="1.2190" />
    <property name="wrist_2_mass" value="1.2190" />
    <property name="gripper_mass" value="0.1879" />

    <property name="shoulder_cog" value="0.0 0.00193 -0.02561" />
    <property name="upper_arm_cog" value="0.0 -0.024201 0.2125" />
    <property name="forearm_cog" value="0.0 0.0265 0.11993" />
    <property name="wrist_1_cog" value="0.0 0.110949 0.01634" />
    <property name="wrist_2_cog" value="0.0 0.0018 0.11099" />
    <property name="wrist_3_cog" value="0.0 0.001159 0.0" />

    <!-- link lengths used in model -->
    <property name="base_height" value=".085" />
    <property name="shoulder_off_x" value="0.08525" />
    <property name="shoulder_height" value=".19" />
    <property name="shoulder_length" value=".015" />
    <property name="arm_length" value="0.2" />
    <property name="upper_arm_length" value="0.2" />
    <property name="forearm_length" value=".13" />
    <property name="wrist_1_length" value=".01" />
    <property name="wrist_2_length" value=".046" />
    <property name="wrist_2_width" value="0.05432" />
    <property name="end_effector_off_x" value="0.067" />


    <!-- limits model -->


    <property name="shoulder_radius" value="0.060" />   <!-- manually measured -->
    <property name="upper_arm_radius" value="0.054" />  <!-- manually measured -->
    <property name="elbow_radius" value="0.060" />      <!-- manually measured -->
    <property name="forearm_radius" value="0.040" />    <!-- manually measured -->
    <property name="wrist_radius" value="0.045" />      <!-- manually measured -->

    <xacro:macro name="cylinder_inertial" params="radius length mass *origin">
        <inertial>
            <mass value="${mass}" />
            <insert_block name="origin" />
            <inertia ixx="${0.0833333 * mass * (3 * radius * radius + length * length)}" ixy="0.0" ixz="0.0"
                     iyy="${0.0833333 * mass * (3 * radius * radius + length * length)}" iyz="0.0"
                     izz="${0.5 * mass * radius * radius}" />
        </inertial>
    </xacro:macro>


    <xacro:macro name="tr5_robot" params="prefix joint_limited">

        <!-- Base %%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%% -->

        <link name="${prefix}base_link" >
            <visual>
                <geometry>
                    <!--box size="0.250 .160 ${shoulder_height}"/ -->
                    <mesh filename="package://tr5_description/meshes/TR5_Base.dae" />
                </geometry>
                <origin xyz="0.0 0.0 0.0" rpy="0.0 0.0 0.0"/>
                <material name="LightGrey">
                    <color rgba="0.7 0.7 0.7 1.0"/>
                </material>
            </visual>
            <collision>
                <geometry>
                    <box size="0.250 .160 ${shoulder_height}"/>
                    <!--<mesh filename="package://ur_description/meshes/ur5/collision/base.stl" />-->
                </geometry>
                <origin xyz="0.0 0.0 ${shoulder_height/2}" rpy="0.0 0.0 0.0"/>
            </collision>
            <xacro:cylinder_inertial radius="0.06" length="0.05" mass="${base_mass}">
                <origin xyz="0.0 0.0 0.0" rpy="0 0 0" />
            </xacro:cylinder_inertial>
        </link>

        <joint name="${prefix}shoulder_pan_joint" type="revolute">
            <parent link="${prefix}base_link" />
            <child link = "${prefix}shoulder_link" />
            <origin xyz="${shoulder_off_x} 0.0 ${base_height}" rpy="0.0 0.0 0.0" />
            <axis xyz="0 0 1" />
            <xacro:unless value="${joint_limited}">
                <limit lower="-1.39626" upper="1.39626" effort="150.0" velocity="0.802851"/>
            </xacro:unless>
            <xacro:if value="${joint_limited}">
                <limit lower="-1.39626" upper="1.39626" effort="150.0" velocity="0.802851"/>
            </xacro:if>
            <dynamics damping="0.0" friction="0.0"/>
        </joint>

        <!-- Shoulder %%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%% -->

        <link name="${prefix}shoulder_link">
            <visual>
                <geometry>
                    <mesh filename="package://tr5_description/meshes/TR5_Shoulder.dae" />
                    <!--cylinder length="${shoulder_length/2}" radius="0.02"/-->
                </geometry>
                <origin xyz="0.0 0.0 0.0" rpy="0.0 0.0 0.0"/>
                <material name="LightGrey">
                    <color rgba="0.7 0.7 0.7 1.0"/>
                </material>
            </visual>
            <collision>
                <geometry>
                    <cylinder length="${shoulder_length/2}" radius="0.02"/>
                </geometry>
                <origin xyz="0.0 0.0 ${shoulder_length/2}" rpy="0.0 0.0 0.0"/>
            </collision>
            <xacro:cylinder_inertial radius="0.06" length="0.15" mass="${shoulder_mass}">
                <origin xyz="0.0 0.0 0.0" rpy="0 0 0" />
            </xacro:cylinder_inertial>
        </link>

        <joint name="${prefix}shoulder_lift_joint" type="revolute">
            <parent link="${prefix}shoulder_link" />
            <child link = "${prefix}upper_arm_link" />
            <origin xyz="0.0 0.0 ${shoulder_height}" rpy="0.0 0 0.0" />
            <axis xyz="0 -1 0" />
            <xacro:unless value="${joint_limited}">
                <limit lower="-0.5934119457" upper="1.151917306" effort="150.0" velocity="0.698132"/>
            </xacro:unless>
            <xacro:if value="${joint_limited}">
                <limit lower="-0.5934119457" upper="1.151917306" effort="150.0" velocity="0.698132"/>
            </xacro:if>
            <dynamics damping="0.0" friction="0.0"/>
        </joint>

        <!--joint name="${prefix}arm_joint" type="fixed">
            <parent link="${prefix}shoulder_link" />
            <child link = "${prefix}upper_arm_link" />
            <origin xyz="0.0 0.0 0.0" rpy="0.0 0.0 0.0" />
            <axis xyz="0 0 0" />
            <dynamics damping="0.0" friction="0.0"/>
        </joint-->


        <!-- Arm %%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%% -->

        <!--link name="${prefix}arm_link">
            <visual>
                <geometry>
                    <box size="0.02 .01 ${arm_length}"/>
                </geometry>
                <origin xyz="0.0 0.0 ${arm_length/2}" rpy="0.0 0.0 0.0"/>
                <material name="LightGrey">
                    <color rgba="0.7 0.7 0.7 1.0"/>
                </material>
            </visual>
            <collision>
                <geometry>
                    <box size="0.02 .01 ${arm_length}"/>
                </geometry>
                <origin xyz="0.0 0.0 ${arm_length/2}" rpy="0.0 0.0 0.0"/>
            </collision>
            <xacro:cylinder_inertial radius="0.06" length="0.56" mass="${arm_mass}">
                <origin xyz="0.0 0.0 0.28" rpy="0 0 0" />
            </xacro:cylinder_inertial>
        </link>

        <joint name="${prefix}shoulder_lift_joint" type="revolute">
            <parent link="${prefix}arm_link" />
            <child link = "${prefix}upper_arm_link" />
            <origin xyz="0.0 0.0 ${arm_length}" rpy="0.0 0 0.0" />
            <axis xyz="0 1 0" />
            <xacro:unless value="${joint_limited}">
                <limit lower="-0.872665" upper="0.872665" effort="150.0" velocity="0.698132"/>
            </xacro:unless>
            <xacro:if value="${joint_limited}">
                <limit lower="-0.872665" upper="0.872665" effort="150.0" velocity="0.698132"/>
            </xacro:if>
            <dynamics damping="0.0" friction="0.0"/>
        </joint-->


        <!-- Upper Arm %%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%% -->

        <link name="${prefix}upper_arm_link">
            <visual>
                <geometry>
                    <mesh filename="package://tr5_description/meshes/TR5_UpperArm.dae" />
                    <!--box size="${upper_arm_length} .02 .01"/-->
                </geometry>
                <origin xyz="0.0 0.0 0.0 " rpy="0.0 0.0 0.0"/>
                <material name="LightGrey">
                    <color rgba="0.7 0.7 0.7 1.0"/>
                </material>
            </visual>
            <collision>
                <geometry>
                    <box size="${upper_arm_length} .02 .01"/>
                </geometry>
                <origin xyz=" ${upper_arm_length/2} 0.0 0.0" rpy="0.0 0.0 0.0"/>
            </collision>
            <xacro:cylinder_inertial radius="0.06" length="0.56" mass="${upper_arm_mass}">
                <origin xyz="0.0 0.0 0.28" rpy="0 0 0" />
            </xacro:cylinder_inertial>
        </link>

        <joint name="${prefix}elbow_joint" type="revolute">
            <parent link="${prefix}upper_arm_link" />
            <child link = "${prefix}forearm_link" />
            <origin xyz="${upper_arm_length} 0.0 0.0 " rpy="0.0 0.0 0.0" />
             <axis xyz="0 -1 0" />
            <xacro:unless value="${joint_limited}">
                <limit lower="-1.7453300007362" upper="0" effort="150.0" velocity="1.74533"/>
            </xacro:unless>
            <xacro:if value="${joint_limited}">
                <limit lower="-1.7453300007362" upper="0" effort="150.0" velocity="1.74533"/>
            </xacro:if>
            <dynamics damping="0.0" friction="0.0"/>
        </joint>

        <!-- Upper Arm %%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%% -->

        <link name="${prefix}forearm_link">
            <visual>
                <geometry>
                    <mesh filename="package://tr5_description/meshes/TR5_ForeArm.dae" />
                    <!--box size="${forearm_length} .02 .01"/-->
                </geometry>
                <origin xyz="0.0 0.0 0.0 " rpy="0.0 0.0 0.0"/>
                <material name="LightGrey">
                    <color rgba="0.7 0.7 0.7 1.0"/>
                </material>
            </visual>
            <collision>
                <geometry>
                    <box size="${forearm_length} .02 .01"/>
                </geometry>
                <origin xyz="${forearm_length/2} 0.0 0.0 " rpy="0.0 0.0 0.0"/>
            </collision>
            <xacro:cylinder_inertial radius="0.06" length="0.5" mass="${forearm_mass}">
                <origin xyz="0.0 0.0 0.25" rpy="0 0 0" />
            </xacro:cylinder_inertial>
        </link>

        <!-- Wrist_pitch %%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%% -->
        
        <joint name="${prefix}wrist_1_joint" type="revolute">
            <parent link="${prefix}forearm_link" />
            <child link = "${prefix}wrist_1_link" />
            <origin xyz="${forearm_length} 0.0 0.0 " rpy="0.0 0.0 0.0" />
            <axis xyz="0 -1 0" />
            <xacro:unless value="${joint_limited}">
                <limit lower="-1.74533" upper="1.74533" effort="28.0" velocity="3.03687"/>
            </xacro:unless>
            <xacro:if value="${joint_limited}">
                <limit lower="-1.74533" upper="1.74533" effort="28.0" velocity="3.03687"/>
            </xacro:if>
            <dynamics damping="0.0" friction="0.0"/>
        </joint>

        <link name="${prefix}wrist_1_link">
            <visual>
                <geometry>
                    <mesh filename="package://tr5_description/meshes/TR5_Wrist_1.dae" />
                    <!--box size="${wrist_1_length} .01 .01"/-->
                </geometry>
                <origin xyz="0.0 0.0 0.0 " rpy="0.0 0.0 0.0"/>
                <material name="LightGrey">
                    <color rgba="0.7 0.7 0.7 1.0"/>
                </material>
            </visual>
            <collision>
                <geometry>
                    <box size="${wrist_1_length} .01 .01"/>
                </geometry>
                <origin xyz="${wrist_1_length/2} 0.0 0.0 " rpy="0.0 0.0 0.0"/>
            </collision>
            <xacro:cylinder_inertial radius="0.6" length="0.12" mass="${wrist_1_mass}">
                <origin xyz="0.0 0.0 0.0" rpy="0 0 0" />
            </xacro:cylinder_inertial>
        </link>

        <!-- Wrist_roll %%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%% -->

        <joint name="${prefix}wrist_2_joint" type="revolute">
            <parent link="${prefix}wrist_1_link" />
            <child link = "${prefix}wrist_2_link" />
            <origin xyz="${wrist_1_length} 0.0 0.0 " rpy="0.0 0.0 0.0" />
            <axis xyz="1 0 0" />
            <xacro:unless value="${joint_limited}">
                <limit lower="-1.7453300007362" upper="1.7453300007362" effort="28.0" velocity="3.07178"/>
            </xacro:unless>
            <xacro:if value="${joint_limited}">
                <limit lower="-1.7453300007362" upper="1.7453300007362" effort="28.0" velocity="3.07178"/>
            </xacro:if>
            <dynamics damping="0.0" friction="0.0"/>
        </joint>

        
        <link name="${prefix}wrist_2_link">
            <visual>
                <geometry>
                    <mesh filename="package://tr5_description/meshes/TR5_Wrist_2.dae" />
                    <!--box size="${wrist_2_length} ${wrist_2_width} .01"/-->
                </geometry>
                <origin xyz="0.0 0.0 0.0 " rpy="0.0 0.0 0.0"/>
                <material name="black">
                    <color rgba="1 1 1 1.0"/>
                </material>
            </visual>
            <collision>
                <geometry>
                    <box size="${wrist_2_length} ${wrist_2_width} .01"/>
                </geometry>
                <origin xyz="${wrist_2_length/2} 0.0 0.0 " rpy="0.0 0.0 0.0"/>
            </collision>
            <xacro:cylinder_inertial radius="0.6" length="0.12" mass="${wrist_2_mass}">
                <origin xyz="0.0 0.0 0.0" rpy="0 0 0" />
            </xacro:cylinder_inertial>
        </link>

        <!-- Finger Left %%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%% -->

        <joint name="${prefix}gripper_1_joint" type="revolute">
            <parent link="${prefix}wrist_2_link" />
            <child link = "${prefix}gripper_1_link" />
            <origin xyz="${wrist_2_length}  ${wrist_2_width/2} 0.0 " rpy="0.0 0.0 0.0" />
            <axis xyz="0 0 1" />
            <xacro:unless value="${joint_limited}">
                <limit lower="0" upper="0.472984" effort="28.0" velocity="3.07178"/>
            </xacro:unless>
            <xacro:if value="${joint_limited}">
                <limit lower="0" upper="0.472984" effort="28.0" velocity="3.07178"/>
            </xacro:if>
            <dynamics damping="0.0" friction="0.0"/>
        </joint>

        <!-- Finger Right %%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%% -->

        <joint name="${prefix}gripper_2_joint" type="revolute">
            <parent link="${prefix}wrist_2_link" />
            <child link = "${prefix}gripper_2_link" />
            <origin xyz="${wrist_2_length}  ${-wrist_2_width/2} 0.0 " rpy="0.0 0.0 0.0" />
            <axis xyz="0 0 -1" />
            <xacro:unless value="${joint_limited}">
                <limit lower="0" upper="0.472984" effort="28.0" velocity="3.07178"/>
            </xacro:unless>
            <xacro:if value="${joint_limited}">
                <limit lower="0" upper="0.472984" effort="28.0" velocity="3.07178"/>
            </xacro:if>
            <dynamics damping="0.0" friction="0.0"/>
        </joint>

        <!-- Gripper %%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%% -->

        <link name="${prefix}gripper_1_link">
            <visual>
                <geometry>
                    <mesh filename="package://tr5_description/meshes/TR5_Finger.dae" />
                    <!--box size="${gripper_length} 0.01 .01"/-->
                </geometry>
                <origin xyz="0.0 0.0 0.0 " rpy="0.0 0.0 0.0"/>
                <material name="black">
                    <color rgba="1 1 1 1.0"/>
                </material>
            </visual>
            <collision>
                <geometry>
                    <mesh filename="package://tr5_description/meshes/TR5_Finger.dae" />
                    <!--box size="${gripper_length} 0.01 .01"/-->
                </geometry>
                <origin xyz="0.0 0.0 0.0 " rpy="0.0 0.0 0.0"/>
            </collision>
            <xacro:cylinder_inertial radius="0.6" length="0.12" mass="${gripper_mass}">
                <origin xyz="0.0 0.0 0.0" rpy="0 0 0" />
            </xacro:cylinder_inertial>
        </link>


        <link name="${prefix}gripper_2_link">
            <visual>
                <geometry>
                    <mesh filename="package://tr5_description/meshes/TR5_Finger.dae" />
                    <!--box size="${gripper_length} 0.01 .01"/-->
                </geometry>
                <origin xyz="0.0 0.0 0.0 " rpy="${pi} 0.0 0.0"/>
                <material name="black">
                    <color rgba="1 1 1 1.0"/>
                </material>
            </visual>
            <collision>
                <geometry>
                    <mesh filename="package://tr5_description/meshes/TR5_Finger.dae" />
                    <!--box size="${gripper_length} 0.01 .01"/-->
                </geometry>
                <origin xyz="0.0 0.0 0.0 " rpy="${pi} 0.0 0.0"/>
            </collision>
            <xacro:cylinder_inertial radius="0.6" length="0.12" mass="${gripper_mass}">
                <origin xyz="0.0 0.0 0.0" rpy="0 0 0" />
            </xacro:cylinder_inertial>
        </link>

        <!-- End Effector %%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%% -->
        <joint name="${prefix}end_effector_joint" type="fixed">
            <parent link="${prefix}wrist_2_link" />
            <child link = "${prefix}end_effector_link" />
            <origin xyz="${wrist_2_length+end_effector_off_x} 0.0 0.0" rpy="0.0 0.0 0.0" />
        </joint>


        <link name="${prefix}end_effector_link">
        </link>

        <!--<xacro:tr_arm_transmission prefix="${prefix}" />-->
        <!--<xacro:tr_arm_gazebo prefix="${prefix}" />-->

        <!-- ROS base_link to UR 'Base' Coordinates transform -->
        <link name="${prefix}base"/>
        <joint name="${prefix}base_link-base_fixed_joint" type="fixed">
            <!-- NOTE: this rotation is only needed as long as base_link itself is
                       not corrected wrt the real robot (ie: rotated over 180
                       degrees)
            -->
            <origin xyz="0 0 0" rpy="0 0 ${-pi}"/>
            <parent link="${prefix}base_link"/>
            <child link="${prefix}base"/>
        </joint>

    </xacro:macro>
</robot>